### ISSUE TITLE
The link "Issue Tracker" in https://www.eisbahn.jp/chrome_mysql_admin/ doesn't work

### ISSUE THREAD

**Issue by igrep** [yoichiro/chrome_mysql_admin#24]
I'm not sure here is the right place to report it.

I found the link to "Issue Tracker" in the bottom of https://www.eisbahn.jp/chrome_mysql_admin/ doesn't work:

- Nothing happened even by clicking.
- The mouse cursor didn't change even by hovering.

I tried it on Chrome, Firefox, IE 11 on Windows, and both reproduced same bug.

**Comment by yoichiro** [comment]
My server stopped. Currently, the server works. Thank you for the reporting!

**Comment by igrep** [comment]
:confused: No, it must be a client side problem - HTML, CSS, or JS.
Because all other links work.

I looked closely to find misspelling: "herf"

From the source:

```html
<a herf="https://github.com/yoichiro/chrome_mysql_admin/issues">Issue Tracker</a>
```

**Comment by yoichiro** [comment]
Oh, sorry. I understand, and it was fixed now.

**Comment by igrep** [comment]
Thank you :smile: :+1: 

P.S. I really liked this extension. I've been looking for a cross-platform and easy-to-install MySQL client. Thank you very much!!
