### ISSUE TITLE
Select text in rows

### ISSUE THREAD

**Issue by benjamw** [yoichiro/chrome_mysql_admin#39]
I was trying to select some of the data in a result row and was unable to do so.

If I could select all the data in a single field, a whole row, or a whole result set, that would be awesome.

Thanks.

**Comment by benjamw** [comment]
To clarify, the result was from a raw SQL statement using the 'Query' button, not a search or plain table view.

**Comment by yoichiro** [comment]
@benjamw Sorry, I don't understand the place which you mentioned as "Query button". Where?

**Comment by benjamw** [comment]
It was a raw query, not a search. I can get a dump of the data using the save as sql feature, but it would be nice to be able to select an individual entry.

**Comment by yoichiro** [comment]
You can copy the selected row values at the following button:

![screenshot_1](https://cloud.githubusercontent.com/assets/261787/13033221/eb2d7da8-d351-11e5-886d-fa0ebf40c693.png)

Is this the expected button by you?

**Comment by benjamw** [comment]
Yes. The highlighted button in the top row of your screen shot is the "Query" button I was referring to earlier. And that red bordered button you've highlighted is the feature I was referring to in my previous comment. This is fine. I can work with this. Thanks.

**Comment by yoichiro** [comment]
@benjamw I see.
