### ISSUE TITLE
White screen on v4.6.1

### ISSUE THREAD

**Issue by benjamw** [yoichiro/chrome_mysql_admin#44]
I've updated the software to use the new "search on enter key" feature, but now it won't load at all.

When I open the app, it shows the basic layout (white screen with grey box where table list would be) but nothing else. No link to localhost, no information anywhere, no nothing. Just a white screen with a grey rectangular sidebar.

Please let me know if you need any more information, and I'm happy to provide.

v4.6.1
Chrome Version 48.0.2564.109 m
Windows 8.1
MySQL 5.6.26-log - MySQL Community Server (GPL)

**Comment by benjamw** [comment]
This may also help... This error was in my console log when I inspected the window.html:

angular.min.js:1 Uncaught Error: [$injector:unpr] Unknown provider: aProvider <- a
http://errors.angularjs.org/1.3.20/$injector/unpr?p0=aProvider%20%3C-%20a

**Comment by benjamw** [comment]
And this error was in the background page when I inspected that:

2016-02-10 22:29:39.131 extensions::lastError:133 Unchecked runtime.lastError while running storage.set: This request exceeds the MAX_WRITE_OPERATIONS_PER_MINUTE quota.
    at chrome-extension://ndgnpnpakfcdjmpgmcaknimfgcldechn/scripts/background.js:71:41reportIfUnchecked @ extensions::lastError:133

**Comment by yoichiro** [comment]
@benjamw Sorry, the previous build might be failed. I'll release the fixed version soon.
