### ISSUE TITLE
Load a MySQL Server on Local Host

### ISSUE THREAD

**Issue by CrypticDesign** [yoichiro/chrome_mysql_admin#65]
Is there anyway to load a MySQL on MySQL Admin? Here's what I've done from a tutorial.
![image](https://user-images.githubusercontent.com/29268859/43989303-2d087086-9cfc-11e8-945c-e19b3d65b5cf.png)
What would go in the User name and password?

**Comment by yoichiro** [comment]
@CrypticDesign This ChromeMySQLAdmin is a client application, not a MySQL server.
