### ISSUE TITLE
MySQL has issue while anyfunctions

### ISSUE THREAD

**Issue by bhidekr** [yoichiro/chrome_mysql_admin#66]
![mysqladmin](https://user-images.githubusercontent.com/27863483/44895159-aa1e6200-ad10-11e8-8bc3-c8be4ac30b7f.png)
I was using the mySQL Admin chrome for db.But firstly there was issue for login. After some time there was issues when when i was create a database. 
I have given screenshot for that.Please go through it and solve the bug.

**Comment by yoichiro** [comment]
@bhidekr If you can reproduce this issue with the latest version 4.10.0 or higher, reopen this issue. Thank you.
