### ISSUE TITLE
Can't cancel a long running request

### ISSUE THREAD

**Issue by stickboyc** [yoichiro/chrome_mysql_admin#67]
Use Case:

I've accidentally run a query that will take many minutes to execute.

Current Behavior:

I am required to wait for the query to complete. (there may be a cancel button in the "Now communicating with MySQL server..." popup, but I can't scroll down to check).

Ideal Behavior:

A button at the top of the popup lets me stop the request.

**Comment by kgingeri** [comment]
Agreed.  This would be a great function.  Or at least let us get back to the process list so we can kill processes (tho that may be more dangerous - especially if it's an update?)

**Comment by yoichiro** [comment]
@stickboyc @kgingeri I have released a new version 4.10.0 supporting to disconnect during running a long query. Also, I added a new button to kill a process on the process list panel. The pull request is #74 Thank you for your feedback!
