### ISSUE TITLE
Can't store connection information as a favorite

### ISSUE THREAD

**Issue by yoichiro** [yoichiro/chrome_mysql_admin#69]
# Expected Behavior

Any connection information can be stored as a favorite normally.

# Actual Behavior

When storing connection information with SSH key, it can't be stored.

# Other

This issue was reported by @fransdw

**Comment by yoichiro** [comment]
It seems that this cause is the limitation of `chrome.storage.sync` storage.

Currently, the limitation is 8,192 bytes (https://developer.chrome.com/apps/storage). Each byte length of SSH private key is about 1,680 bytes. If we assume that the byte length of other items is 100 bytes, the byte length of each connection information is 1,780 bytes. That is, in the current version of this app, users can store only **four** connection information...

**Comment by yoichiro** [comment]
To solve the root cause, I might need to change the `chrome.storage.sync` to `chrome.storage.local` to increase the capacity. Of course, the connection information will not be shared between multiple devices, but I think that to solve this issue is important than the sharing functionality.

**Comment by yoichiro** [comment]
I have released a new version 4.8.0 to migrate the storage to store configurations from `chrome.storage.sync` to `chrome.storage.local`. All configurations are kept by moving sync to local automatically. By migrating, the configurations no longer shared, but we could get a large storage to store them. Thus, I think that this issue was fixed.

**Comment by yoichiro** [comment]
@fransdw Could you confirm whether this issue is fixed on your environment with the latest version?

**Comment by fransdewet** [comment]
I am on my other account here ... 

I can confirm, this works in my situation.  Thanks!!!
